export default {
  cart: [],
  buyer: [],
  orders: [],
  products: [
    {
      id: '1',
      image: 'https://i.ibb.co/LpYrVV1/visual-studio.png',
      title: 'VS Code',
      price: 25,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '2',
      image: 'https://i.ibb.co/Jt6VnsV/sass.png',
      title: 'SASS',
      price: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '3',
      image: 'https://i.ibb.co/W0r230X/python.png',
      title: 'Python',
      price: 4,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '4',
      image: 'https://i.ibb.co/VSc7S0t/physics.png',
      title: 'ReactJS',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '5',
      image: 'https://i.ibb.co/rcVrjxW/php.png',
      title: 'PHP',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '6',
      image: 'https://i.ibb.co/TPXk0k1/nodejs.png',
      title: 'NodeJS',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '7',
      image: 'https://i.ibb.co/4MjG9tn/mysql.png',
      title: 'MySQL',
      price: 25,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '8',
      image: 'https://i.ibb.co/jZshXH6/linux.png',
      title: 'Linux',
      price: 10,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '9',
      image: 'https://i.ibb.co/gyD0sZX/js.png',
      title: 'JavaScript',
      price: 4,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '10',
      image: 'https://i.ibb.co/DY8hp45/java.png',
      title: 'Java',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '11',
      image: 'https://i.ibb.co/6bmtcv4/html-5.png',
      title: 'HTML',
      price: 2,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '12',
      image: 'https://i.ibb.co/Kj5TJX3/github.png',
      title: 'GitHub',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '13',
      image: 'https://i.ibb.co/t2hYsc6/figma.png',
      title: 'Figma',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '14',
      image: 'https://i.ibb.co/6rWsPcw/css-3.png',
      title: 'CSS',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
    {
      id: '15',
      image: 'https://i.ibb.co/n3rXjPw/c-sharp.png',
      title: 'C #',
      price: 35,
      description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit',
    },
  ],
};
